Added loop option for slow servers

diff --git a/tssh b/tssh
--- a/tssh
+++ b/tssh
@@ -47,6 +47,24 @@ function openShell ()
   fi
   ssh -t -t -o "StrictHostKeyChecking no" $SSHPARAMS
 }
+function openShellLoop ()
+{
+  IP=${1:-"127.0.0.1"}
+  PORT=${2:-"22"}
+  USER=${3:-"root"}
+  IFILE=${4:-"/root/.ssh/id_rsa"}
+  SSHPARAMS=" -p $PORT $USER@$IP -i $IFILE "
+  if [ $SHOW_CONNECT_INFO -eq 1 ];
+  then
+    echo "Connecting to $USER@$IP:$PORT [$TSSH_HOST] using $IFILE"
+  fi
+  COUNTER=0
+  until ssh -t -t -o "StrictHostKeyChecking no" -o "ConnectTimeout 2" $SSHPARAMS 2>/dev/null
+  do
+    echo -n "$COUNTER "
+    COUNTER=$(expr $COUNTER + 1)
+  done
+}
 
 function searchTextFile ()
 {
@@ -202,6 +220,33 @@ function sshConnect ()
     echo "$DESTINATION not found."
   fi
 }
+function sshLoop ()
+{
+  DESTINATION=${1:-"localhost"}
+  if [ $TEXTFILE_ENABLED -eq 1 ] && [ $TSSH_HOSTFOUND -eq 0 ];
+  then
+    searchTextFile $DESTINATION
+    if [ $TSSH_HOSTFOUND -eq 1 ];
+    then
+      openShellLoop $TSSH_IP $TSSH_PORT $TSSH_USER $KEYS_DIR/$TSSH_KEY
+    fi
+  fi
+  if [ $PGSQL_ENABLED -eq 1 ] && [ $TSSH_HOSTFOUND -eq 0 ];
+  then
+    searchPSQL $PSQL_SSH_HOST $PSQL_SSH_PORT $PSQL_SSH_USER $PSQL_SSH_KEY $PSQL_LOCAL_PORT $DESTINATION
+    if [ $TSSH_HOSTFOUND -eq 1 ];
+    then
+      extractPSQLkey $PSQL_SSH_HOST $PSQL_SSH_PORT $PSQL_SSH_USER $PSQL_SSH_KEY $PSQL_LOCAL_PORT $TSSH_KEY
+      openShellLoop $TSSH_IP $TSSH_PORT $TSSH_USER $TEMP_DIR/$TSSH_KEY
+      rm -f $TEMP_DIR/$TSSH_KEY
+    fi
+  fi
+  if [ $TSSH_HOSTFOUND -eq 0 ];
+  then
+    echo "$DESTINATION not found."
+  fi
+}
+
 function pingHost ()
 {
   DESTINATION=${1:-"localhost"}
@@ -419,6 +464,15 @@ else
 		  exit 255
 		fi
 		;;
+    loop)       if [ $# -gt 1 ];
+                then
+                  DESTINATION=$2
+                  sshLoop $DESTINATION
+                else
+                  echo "Need another parameter to connect to."
+                  exit 255
+                fi
+                ;;
     nmap)	if [ $# -gt 1 ];
 		then
 		  DESTINATION=$2
